[features]
seeds = false
skip-lint = false

[programs.localnet]
hera_solana = "EhVhhvQEhyRELEKSsivfSo1YFxKa4btgspR9WGjcP6Ei"

[programs.devnet]
hera_solana = "EhVhhvQEhyRELEKSsivfSo1YFxKa4btgspR9WGjcP6Ei"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/gabrielunruh/.config/solana/hera_prog.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
